TEST_DATA=data/official/data/sample_annotation/text0$(L2).conll

TESTCR_DIR=data/test_cr/$(L2)
TESTCR_DE_DIR=data/test_cr/de
TESTCR_RU_DIR=data/test_cr/ru
TESTCR_TMP=tmp/test_cr/$(L2)

############################################### STAGE 1 ##################################################
################################# LOAD TEST DATA AND TEXTO ANALYSE IT ####################################
##########################################################################################################

TESTCR_TECTO_DIR=$(TESTCR_DIR)/01.tecto
TESTCR_TECTO_DE_DIR=$(TESTCR_DE_DIR)/01.tecto
TESTCR_TECTO_RU_DIR=$(TESTCR_RU_DIR)/01.tecto

tecto_test_ru : $(TESTCR_TECTO_RU_DIR)/done
$(TESTCR_TECTO_RU_DIR)/done :
	mkdir -p $(dir $@)
	$(TREEX) -Lru -Ssrc \
		Read::CoNLLTokens from='!$(TEST_DATA)' \
		Scen::Analysis::RU tokenized=1 default_functor='???' \
		Write::Treex storable=1 path='$(dir $@)' && \
	touch $@

tecto_test_de : $(TESTCR_TECTO_DE_DIR)/done
$(TESTCR_TECTO_DE_DIR)/done :
	mkdir -p $(dir $@)
	for i in $(TEST_DATA); do \
		scripts/german_parse.sh $$i $(dir $@) 1; \
	done
	$(TREEX) -Ssrc \
		Read::CoNLL2009 language=$(L2) use_p_attribs=1 doc_reset_sent_id=1 from='!$(dir $@)/*.conll' \
		Util::Eval anode='my $$nf = join "|", map {ucfirst $$_} split /\|/, $$anode->conll_feat; $$anode->set_tag($$anode->conll_pos." ".$$nf)' \
		A2A::ConvertTags input_driver=de::conll2009 \
		HamleDT::DE::Harmonize \
		Util::Eval anode='$$anode->set_afun($$anode->deprel)' \
		Scen::Analysis::DE default_functor='???' \
		Write::Treex storable=1 path='$(dir $@)' && \
	touch $@

############################################### STAGE 2 ##################################################
########################### RESOLVE COREFERENCE ON THE TEST DATA AND EVALUATE ############################
##########################################################################################################

RUNS_DIR=$(TESTCR_DIR)/02.coref_resolved

DATE := $(shell date +%Y-%m-%d_%H-%M-%S)
LAST_TRY := $(shell ls -d -t $(RUNS_DIR)/[0-9]* 2>/dev/null | head -n 1)
NEW_NUM  := $(shell perl -e '$$m=0; for(<$(RUNS_DIR)/*>){/\/(\d+)_/ and $$1 > $$m and $$m=$$1;} printf "%03d", $$m+1;')
NEW_TRY  := $(RUNS_DIR)/$(NEW_NUM)_$(DATE)

UC_L2:=$(shell echo $(L2) | tr a-z A-Z)

INPUT_PATTERN=text0$(L2)
DEV=1
ifeq ($(DEV),0)
INPUT_PATTERN=*_$(L2)
endif

resolve_test : $(TESTCR_TECTO_DIR)/done
	mkdir -p $(NEW_TRY)/resolve
	echo "$(D)" > $(NEW_TRY)/description
	$(TREEX) -L$(L2) -Ssrc \
		Read::Treex from='!$(dir $<)/$(INPUT_PATTERN).streex' \
		Coref::$(UC_L2)::RelPron::Resolve \
		Coref::$(UC_L2)::DemonPron::Resolve \
		Coref::$(UC_L2)::PersPron::Resolve \
		Coref::$(UC_L2)::Noun::Resolve \
		Coref::MarkMentionsForScorer layer=a only_heads=0 \
		Write::SemEval2010 layer=a path='$(NEW_TRY)/resolve' \
		Write::Treex storable=1 path='$(NEW_TRY)/resolve'

SCORER=/net/work/people/mnovak/tools/x86_64/coref_scorer/v8.01/scorer.pl

eval_test :
	mkdir -p $(NEW_TRY)/eval
	ls $(TEST_DATA) | sort | xargs cat | sed 's/(__); __/text0$(L2)/' > $(NEW_TRY)/eval/all.key.conll
	find $(NEW_TRY)/resolve/ -name '*.conll' | sort | xargs cat | cut --complement -f18 > $(NEW_TRY)/eval/all.response.conll
	$(SCORER) all $(NEW_TRY)/eval/all.key.conll $(NEW_TRY)/eval/all.response.conll > $(NEW_TRY)/eval/score.txt
	fscore_avg=`cat $(NEW_TRY)/eval/score.txt | grep Coreference | head -n4 | cut -f3 | cut -f2 -d' ' | cut -f1 -d'%' | awk '{ total += $$1; count++ } END { print total/count }'`; \
	desc=`cat $(NEW_TRY)/description`; \
	echo -e "$(DATE)\t$$fscore_avg\t$(NEW_TRY)\t$$desc" >> results.$(L2).txt
