LANGUAGE=de

################## monolingual #####################

DATA_NAME=official

# original W2A
TRAIN_DATA=../../../data/bitext_analysis/en_de/07.add_rulebased/train-small_dev.list
DEV_DATA=../../../data/bitext_analysis/en_de/07.add_rulebased/dev.list
EVAL_DATA=../../../data/bitext_analysis/en_de/07.add_rulebased/eval.list
